unit TestConditionForm;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Vcl.Dialogs, Winapi.Windows, System.SysUtils, ConditionForm,
  Vcl.Graphics, System.Variants, Winapi.Messages, Vcl.StdCtrls, Vcl.Controls, Vcl.Forms,
  System.Classes;

type
  // Test methods for class TfrmFunction

  TestTfrmFunction = class(TTestCase)
  strict private
    FfrmCondition: TfrmCondition;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestLoginCheckEmpty;
    procedure TestLoginCheckNotfound;
    procedure TestLoginCheckIncorrect;
    procedure TestLoginCheckOK;
  end;

implementation

procedure TestTfrmFunction.SetUp;
begin
  FfrmCondition := TfrmCondition.Create(nil);
end;

procedure TestTfrmFunction.TearDown;
begin
  FfrmCondition.Free;
  FfrmCondition := nil;
end;

procedure TestTfrmFunction.TestLoginCheckEmpty;
var
  ReturnValue: Integer;
begin
  ReturnValue := FfrmCondition.LoginCheck('', '');
  CheckEquals(ReturnValue, LOGIN_RESULT_EMPTY, '공백 확인');
end;

procedure TestTfrmFunction.TestLoginCheckNotfound;
var
  ReturnValue: Integer;
begin
  ReturnValue := FfrmCondition.LoginCheck('no_id', '');
  CheckEquals(ReturnValue, LOGIN_RESULT_NOTFOUND_ID, 'Id 없음');
end;

procedure TestTfrmFunction.TestLoginCheckIncorrect;
var
  ReturnValue: Integer;
begin
  ReturnValue := FfrmCondition.LoginCheck('abc', '0000');
  CheckEquals(ReturnValue, LOGIN_RESULT_INCORRECT, 'Id와 비밀번호 비일치');
end;

procedure TestTfrmFunction.TestLoginCheckOK;
var
  ReturnValue: Integer;
begin
  ReturnValue := FfrmCondition.LoginCheck('abc', '123');
  CheckEquals(ReturnValue, LOGIN_RESULT_OK, 'OK');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTfrmFunction.Suite);
end.

