unit TestLoopForm;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Vcl.Dialogs, Winapi.Windows, System.SysUtils, LoopForm, Vcl.Graphics,
  System.Variants, Winapi.Messages, Vcl.StdCtrls, Vcl.Controls, Vcl.Forms,
  System.Classes;

type
  // Test methods for class TForm3

  TestTfrmLoop = class(TTestCase)
  strict private
    FfrmLoop: TfrmLoop;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCalcOddNumSum;

    procedure TestLoadData;
  end;

implementation

procedure TestTfrmLoop.SetUp;
begin
  FfrmLoop := TfrmLoop.Create(nil);
end;

procedure TestTfrmLoop.TearDown;
begin
  FfrmLoop.Free;
  FfrmLoop := nil;
end;

procedure TestTfrmLoop.TestCalcOddNumSum;
var
  ReturnValue: Integer;
begin
  ReturnValue := FfrmLoop.CalcOddNumSum(2, 5);
  CheckEquals(ReturnValue, 8, '3, 5');

  ReturnValue := FfrmLoop.CalcOddNumSum(1, 10);
  CheckEquals(ReturnValue, 25, 'Odd count : 1 to 10');

  ReturnValue := FfrmLoop.CalcOddNumSum(23, 231);
  CheckEquals(ReturnValue, 13335, 'Odd count : 23 to 231');
end;

procedure TestTfrmLoop.TestLoadData;
var
  ReturnValue: Boolean;
begin
  ReturnValue := FfrmLoop.CheckLoadData;

  Check(ReturnValue, 'DataSnap 데이터 로드');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTfrmLoop.Suite);
end.

